// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, camel_case_types, depend_on_referenced_packages

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../metrics/runtime.dart';
import '../types/ids.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `parse_hash`, `parse_priority`

/// AetherOS runtime'ı başlat.
///
/// Flutter uygulaması açılırken (main() veya splash screen'de)
/// bir kez çağrılır. İkinci çağrı hata döner.
///
/// `db_path`: SQLite/sled veritabanı konumu
///   Android: `/data/data/<package>/databases/aetheros.db`
///   iOS:     `<documents>/aetheros.db`
///
/// `worker_count`: paralel WASM worker sayısı
///   Mobil için 2-4 önerilir.
Future<void> initializeRuntime(
        {required String dbPath, required int workerCount}) =>
    RustLib.instance.api.crateBridgeApiInitializeRuntime(
        dbPath: dbPath, workerCount: workerCount);

/// Runtime'ın çalışıp çalışmadığını kontrol et.
Future<bool> isRuntimeReady() =>
    RustLib.instance.api.crateBridgeApiIsRuntimeReady();

/// Runtime bilgilerini al (versiyon, backend, worker sayısı).
Future<RuntimeInfo> getRuntimeInfo() =>
    RustLib.instance.api.crateBridgeApiGetRuntimeInfo();

/// Task gönder → task_id döner.
///
/// WASM modülü yoksa (wasm_module_hash == "") task yine kabul
/// edilir; runtime Failed olarak işaretler.
///
/// Örnek (Dart):
/// ```dart
/// final taskId = await AetherApi.submitTask(TaskRequest(
///   wasmModuleHash: hash,
///   entrypoint: "run",
///   priority: "normal",
///   timeoutMs: 30000,
///   maxRetries: 3,
/// ));
/// ```
Future<String> submitTask({required TaskRequest request}) =>
    RustLib.instance.api.crateBridgeApiSubmitTask(request: request);

/// Task durumunu sorgula.
Future<TaskStatusResponse> getTaskStatus({required String taskId}) =>
    RustLib.instance.api.crateBridgeApiGetTaskStatus(taskId: taskId);

/// Tüm task'ları listele (son N tane).
Future<List<TaskStatusResponse>> listTasks({required int limit}) =>
    RustLib.instance.api.crateBridgeApiListTasks(limit: limit);

/// WASM modülü yükle → hash döner.
///
/// Flutter, dosyayı bytes olarak Rust'a verir.
/// Rust, ModuleStore'a kaydeder ve SHA-256 hash döner.
/// Sonraki task'larda bu hash kullanılır.
///
/// Örnek (Dart):
/// ```dart
/// final bytes = await File("my_module.wasm").readAsBytes();
/// final hash = await AetherApi.uploadWasmModule(bytes: bytes);
/// ```
Future<ModuleUploadResponse> uploadWasmModule({required List<int> bytes}) =>
    RustLib.instance.api.crateBridgeApiUploadWasmModule(bytes: bytes);

/// Anlık metrik görüntüsü al.
Future<MetricsSnapshot> getMetrics() =>
    RustLib.instance.api.crateBridgeApiGetMetrics();
