// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, camel_case_types, depend_on_referenced_packages

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

@freezed
sealed class ModuleUploadResponse with _$ModuleUploadResponse {
  const factory ModuleUploadResponse({
    required String hash,
    required BigInt size,
  }) = _ModuleUploadResponse;
}

/// Flutter'ın task göndermek için kullandığı tip.
///
/// wasm_module_hash: 64 karakter hex string (SHA-256)
/// Boş string → modülsüz task (test için)
@freezed
sealed class TaskRequest with _$TaskRequest {
  const factory TaskRequest({
    required String wasmModuleHash,
    required String entrypoint,
    required String priority,
    required BigInt timeoutMs,
    required int maxRetries,
  }) = _TaskRequest;
}

/// Flutter'ın task durumunu göstermek için kullandığı tip.
@freezed
sealed class TaskStatusResponse with _$TaskStatusResponse {
  const factory TaskStatusResponse({
    required String taskId,
    required String state,
    required PlatformInt64 createdAt,
    required PlatformInt64 updatedAt,
    required int attempts,
    String? errorMessage,
  }) = _TaskStatusResponse;
}
