// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, camel_case_types, depend_on_referenced_packages

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../types/ids.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

class RuntimeInfo {
  final RuntimeId id;
  final String label;
  final bool healthy;

  const RuntimeInfo({
    required this.id,
    required this.label,
    required this.healthy,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ healthy.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          healthy == other.healthy;
}
