// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, camel_case_types, depend_on_referenced_packages

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class MetricsSnapshot {
  final BigInt activeWorkers;
  final BigInt queuedTasks;
  final BigInt completedTasks;
  final BigInt failedTasks;
  final BigInt retriedTasks;

  const MetricsSnapshot({
    required this.activeWorkers,
    required this.queuedTasks,
    required this.completedTasks,
    required this.failedTasks,
    required this.retriedTasks,
  });

  @override
  int get hashCode =>
      activeWorkers.hashCode ^
      queuedTasks.hashCode ^
      completedTasks.hashCode ^
      failedTasks.hashCode ^
      retriedTasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MetricsSnapshot &&
          runtimeType == other.runtimeType &&
          activeWorkers == other.activeWorkers &&
          queuedTasks == other.queuedTasks &&
          completedTasks == other.completedTasks &&
          failedTasks == other.failedTasks &&
          retriedTasks == other.retriedTasks;
}
