// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, camel_case_types, depend_on_referenced_packages

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'bridge/api.dart';
import 'bridge/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'metrics/runtime.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';
import 'types/ids.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateBridgeApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 757487708;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'aetheros',
    ioDirectory: '../target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<MetricsSnapshot> crateBridgeApiGetMetrics();

  Future<RuntimeInfo> crateBridgeApiGetRuntimeInfo();

  Future<TaskStatusResponse> crateBridgeApiGetTaskStatus(
      {required String taskId});

  Future<void> crateBridgeApiInitApp();

  Future<void> crateBridgeApiInitializeRuntime(
      {required String dbPath, required int workerCount});

  Future<bool> crateBridgeApiIsRuntimeReady();

  Future<List<TaskStatusResponse>> crateBridgeApiListTasks(
      {required int limit});

  Future<String> crateBridgeApiSubmitTask({required TaskRequest request});

  Future<ModuleUploadResponse> crateBridgeApiUploadWasmModule(
      {required List<int> bytes});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<MetricsSnapshot> crateBridgeApiGetMetrics() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_metrics_snapshot,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateBridgeApiGetMetricsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiGetMetricsConstMeta => const TaskConstMeta(
        debugName: "get_metrics",
        argNames: [],
      );

  @override
  Future<RuntimeInfo> crateBridgeApiGetRuntimeInfo() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_runtime_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateBridgeApiGetRuntimeInfoConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiGetRuntimeInfoConstMeta =>
      const TaskConstMeta(
        debugName: "get_runtime_info",
        argNames: [],
      );

  @override
  Future<TaskStatusResponse> crateBridgeApiGetTaskStatus(
      {required String taskId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(taskId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_task_status_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateBridgeApiGetTaskStatusConstMeta,
      argValues: [taskId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiGetTaskStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_task_status",
        argNames: ["taskId"],
      );

  @override
  Future<void> crateBridgeApiInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateBridgeApiInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateBridgeApiInitializeRuntime(
      {required String dbPath, required int workerCount}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_u_32(workerCount, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateBridgeApiInitializeRuntimeConstMeta,
      argValues: [dbPath, workerCount],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiInitializeRuntimeConstMeta =>
      const TaskConstMeta(
        debugName: "initialize_runtime",
        argNames: ["dbPath", "workerCount"],
      );

  @override
  Future<bool> crateBridgeApiIsRuntimeReady() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateBridgeApiIsRuntimeReadyConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiIsRuntimeReadyConstMeta =>
      const TaskConstMeta(
        debugName: "is_runtime_ready",
        argNames: [],
      );

  @override
  Future<List<TaskStatusResponse>> crateBridgeApiListTasks(
      {required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_u_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_task_status_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateBridgeApiListTasksConstMeta,
      argValues: [limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiListTasksConstMeta => const TaskConstMeta(
        debugName: "list_tasks",
        argNames: ["limit"],
      );

  @override
  Future<String> crateBridgeApiSubmitTask({required TaskRequest request}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_task_request(request, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateBridgeApiSubmitTaskConstMeta,
      argValues: [request],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiSubmitTaskConstMeta => const TaskConstMeta(
        debugName: "submit_task",
        argNames: ["request"],
      );

  @override
  Future<ModuleUploadResponse> crateBridgeApiUploadWasmModule(
      {required List<int> bytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(bytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_module_upload_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateBridgeApiUploadWasmModuleConstMeta,
      argValues: [bytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateBridgeApiUploadWasmModuleConstMeta =>
      const TaskConstMeta(
        debugName: "upload_wasm_module",
        argNames: ["bytes"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  UuidValue dco_decode_Uuid(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UuidValue.fromByteList(dco_decode_list_prim_u_8_strict(raw));
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  TaskRequest dco_decode_box_autoadd_task_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_request(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaskStatusResponse> dco_decode_list_task_status_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_status_response).toList();
  }

  @protected
  MetricsSnapshot dco_decode_metrics_snapshot(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return MetricsSnapshot(
      activeWorkers: dco_decode_u_64(arr[0]),
      queuedTasks: dco_decode_u_64(arr[1]),
      completedTasks: dco_decode_u_64(arr[2]),
      failedTasks: dco_decode_u_64(arr[3]),
      retriedTasks: dco_decode_u_64(arr[4]),
    );
  }

  @protected
  ModuleUploadResponse dco_decode_module_upload_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ModuleUploadResponse(
      hash: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  RuntimeId dco_decode_runtime_id(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return RuntimeId(
      field0: dco_decode_Uuid(arr[0]),
    );
  }

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RuntimeInfo(
      version: dco_decode_String(arr[0]),
      isRunning: dco_decode_bool(arr[1]),
      backend: dco_decode_String(arr[2]),
      workerCount: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  TaskRequest dco_decode_task_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TaskRequest(
      wasmModuleHash: dco_decode_String(arr[0]),
      entrypoint: dco_decode_String(arr[1]),
      priority: dco_decode_String(arr[2]),
      timeoutMs: dco_decode_u_64(arr[3]),
      maxRetries: dco_decode_u_32(arr[4]),
    );
  }

  @protected
  TaskStatusResponse dco_decode_task_status_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TaskStatusResponse(
      taskId: dco_decode_String(arr[0]),
      state: dco_decode_String(arr[1]),
      createdAt: dco_decode_i_64(arr[2]),
      updatedAt: dco_decode_i_64(arr[3]),
      attempts: dco_decode_u_32(arr[4]),
      errorMessage: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return UuidValue.fromByteList(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  TaskRequest sse_decode_box_autoadd_task_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_request(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaskStatusResponse> sse_decode_list_task_status_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskStatusResponse>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_status_response(deserializer));
    }
    return ans_;
  }

  @protected
  MetricsSnapshot sse_decode_metrics_snapshot(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_activeWorkers = sse_decode_u_64(deserializer);
    var var_queuedTasks = sse_decode_u_64(deserializer);
    var var_completedTasks = sse_decode_u_64(deserializer);
    var var_failedTasks = sse_decode_u_64(deserializer);
    var var_retriedTasks = sse_decode_u_64(deserializer);
    return MetricsSnapshot(
        activeWorkers: var_activeWorkers,
        queuedTasks: var_queuedTasks,
        completedTasks: var_completedTasks,
        failedTasks: var_failedTasks,
        retriedTasks: var_retriedTasks);
  }

  @protected
  ModuleUploadResponse sse_decode_module_upload_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    return ModuleUploadResponse(hash: var_hash, size: var_size);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RuntimeId sse_decode_runtime_id(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_Uuid(deserializer);
    return RuntimeId(field0: var_field0);
  }

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_version = sse_decode_String(deserializer);
    var var_isRunning = sse_decode_bool(deserializer);
    var var_backend = sse_decode_String(deserializer);
    var var_workerCount = sse_decode_u_32(deserializer);
    return RuntimeInfo(version: var_version, isRunning: var_isRunning, backend: var_backend, workerCount: var_workerCount);
  }

  @protected
  TaskRequest sse_decode_task_request(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_wasmModuleHash = sse_decode_String(deserializer);
    var var_entrypoint = sse_decode_String(deserializer);
    var var_priority = sse_decode_String(deserializer);
    var var_timeoutMs = sse_decode_u_64(deserializer);
    var var_maxRetries = sse_decode_u_32(deserializer);
    return TaskRequest(
        wasmModuleHash: var_wasmModuleHash,
        entrypoint: var_entrypoint,
        priority: var_priority,
        timeoutMs: var_timeoutMs,
        maxRetries: var_maxRetries);
  }

  @protected
  TaskStatusResponse sse_decode_task_status_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_taskId = sse_decode_String(deserializer);
    var var_state = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_i_64(deserializer);
    var var_updatedAt = sse_decode_i_64(deserializer);
    var var_attempts = sse_decode_u_32(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return TaskStatusResponse(
        taskId: var_taskId,
        state: var_state,
        createdAt: var_createdAt,
        updatedAt: var_updatedAt,
        attempts: var_attempts,
        errorMessage: var_errorMessage);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.toBytes(), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_task_request(
      TaskRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_request(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_task_status_response(
      List<TaskStatusResponse> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_status_response(item, serializer);
    }
  }

  @protected
  void sse_encode_metrics_snapshot(
      MetricsSnapshot self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.activeWorkers, serializer);
    sse_encode_u_64(self.queuedTasks, serializer);
    sse_encode_u_64(self.completedTasks, serializer);
    sse_encode_u_64(self.failedTasks, serializer);
    sse_encode_u_64(self.retriedTasks, serializer);
  }

  @protected
  void sse_encode_module_upload_response(
      ModuleUploadResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_u_64(self.size, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_runtime_id(RuntimeId self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Uuid(self.field0, serializer);
  }

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.version, serializer);
    sse_encode_bool(self.isRunning, serializer);
    sse_encode_String(self.backend, serializer);
    sse_encode_u_32(self.workerCount, serializer);
  }

  @protected
  void sse_encode_task_request(TaskRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.wasmModuleHash, serializer);
    sse_encode_String(self.entrypoint, serializer);
    sse_encode_String(self.priority, serializer);
    sse_encode_u_64(self.timeoutMs, serializer);
    sse_encode_u_32(self.maxRetries, serializer);
  }

  @protected
  void sse_encode_task_status_response(
      TaskStatusResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.taskId, serializer);
    sse_encode_String(self.state, serializer);
    sse_encode_i_64(self.createdAt, serializer);
    sse_encode_i_64(self.updatedAt, serializer);
    sse_encode_u_32(self.attempts, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
