// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, camel_case_types, depend_on_referenced_packages

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'bridge/api.dart';
import 'bridge/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'metrics/runtime.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'package:uuid/uuid.dart';
import 'registry/runtime.dart';
import 'types/ids.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  UuidValue dco_decode_Uuid(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  TaskRequest dco_decode_box_autoadd_task_request(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TaskStatusResponse> dco_decode_list_task_status_response(dynamic raw);

  @protected
  MetricsSnapshot dco_decode_metrics_snapshot(dynamic raw);

  @protected
  ModuleUploadResponse dco_decode_module_upload_response(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  RuntimeId dco_decode_runtime_id(dynamic raw);

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw);

  @protected
  TaskRequest dco_decode_task_request(dynamic raw);

  @protected
  TaskStatusResponse dco_decode_task_status_response(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  UuidValue sse_decode_Uuid(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  TaskRequest sse_decode_box_autoadd_task_request(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TaskStatusResponse> sse_decode_list_task_status_response(
      SseDeserializer deserializer);

  @protected
  MetricsSnapshot sse_decode_metrics_snapshot(SseDeserializer deserializer);

  @protected
  ModuleUploadResponse sse_decode_module_upload_response(
      SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  RuntimeId sse_decode_runtime_id(SseDeserializer deserializer);

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer);

  @protected
  TaskRequest sse_decode_task_request(SseDeserializer deserializer);

  @protected
  TaskStatusResponse sse_decode_task_status_response(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_Uuid(UuidValue self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_task_request(
      TaskRequest self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_task_status_response(
      List<TaskStatusResponse> self, SseSerializer serializer);

  @protected
  void sse_encode_metrics_snapshot(
      MetricsSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_module_upload_response(
      ModuleUploadResponse self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_runtime_id(RuntimeId self, SseSerializer serializer);

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_task_request(TaskRequest self, SseSerializer serializer);

  @protected
  void sse_encode_task_status_response(
      TaskStatusResponse self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
